/**
 * Created by xuds on 2015/3/14.
 */
$(function(){
    var bodyHeight=(document.body.scrollHeight-70)+"px";
    var limitWidth=1200;//移动端与PC端的阈值
    $(".cstm-panel-body-height").css("height",bodyHeight);
    $("#operateUserPane").click(function(){
        if(document.body.scrollWidth>=limitWidth){
            $(".cstm-qunmumber-pane").fadeToggle();
        }else{
            $(".cstm-qunmumber-pane").fadeIn();
            $(".cstm-video-pane").fadeOut();
            $(".cstm-chart-pane").fadeOut();
        }
    });
    $("#operateChartPane").click(function(){
        if(document.body.scrollWidth>=limitWidth){
            $(".cstm-chart-pane").fadeToggle();
        }else{
            $(".cstm-qunmumber-pane").fadeOut();
            $(".cstm-video-pane").fadeOut();
            $(".cstm-chart-pane").fadeIn();
        }
    });
    $("#hiddenUserPane").click(function(){
        if(document.body.scrollWidth>=limitWidth){
            $(".cstm-qunmumber-pane").fadeOut();
            $(".cstm-video-pane").fadeIn();
        }else{
            $(".cstm-qunmumber-pane").fadeOut();
            $(".cstm-video-pane").fadeIn();
            $(".cstm-chart-pane").fadeOut();
        }
    });
    $("#hiddenChartPane").click(function(){
        if(document.body.scrollWidth>=limitWidth){
            $(".cstm-chart-pane").fadeOut();
            $(".cstm-video-pane").fadeIn();
        }else{
            $(".cstm-qunmumber-pane").fadeOut();
            $(".cstm-video-pane").fadeIn();
            $(".cstm-chart-pane").fadeOut();
        }
    });
$("#operateBadgeChartPane").click(function(){
    if(document.body.scrollWidth>=limitWidth){
        $(".cstm-chart-pane").fadeToggle();
    }else{
        $(".cstm-qunmumber-pane").fadeOut();
        $(".cstm-video-pane").fadeOut();
        $(".cstm-chart-pane").fadeIn();
    }
});
});